name: Realse

on:
  push:
    tags:
    - 'v*'

env:
  SOLUTION_FILE_PATH: metamod/ascron
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build-win32:
    runs-on: windows-latest

    steps:    
    - name: Git Clone Metamod
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: DrAbcOfficial/metamod-fallguys
        path: metamod
    
    - name: Git Clone This
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: DrAbcOfficial/ascron
        path: metamod/ascron

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Zipping All
      uses: vimtor/action-zip@v1
      with:
          files: metamod/build/addons/metamod/dlls/ascron.dll
          dest: ascron-windows-x86.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          name: ascron-${{ github.ref }}
          files: |
            ascron-windows-x86.zip
    
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Build Enviroment
      uses: ConorMacBride/install-package@v1
      with:
        apt: make build-essential gcc gcc-multilib g++-multilib
          
    - name: Git Clone Metamod
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: DrAbcOfficial/metamod-fallguys
        path: metamod
    
    - name: Git Clone This
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: DrAbcOfficial/ascron
        path: metamod/ascron

    - name: Build
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RELEASE .. && make && mv libascron.so ascron.so

    - name: Zipping All
      uses: vimtor/action-zip@v1
      with:
          files: ${{env.SOLUTION_FILE_PATH}}/build/ascron.so
          dest: ascron-ubuntu-i386.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          name: ascron-${{ github.ref }}
          files: |
            ascron-ubuntu-i386.zip
